[versions]
compose = "1.4.1"
composeMaterial = "1.4.1"
composeCompiler = "1.3.2"
composeLifecycle = "2.6.1"
composeDestinations = "1.8.38-beta"
composeConstraintLayout = "1.0.1"
composeMaterial3 = "1.0.1"

hilt = "2.44"
androidCore = "1.10.0"
room = "2.5.1"
dataStore = "1.0.0"
kotlinCoroutines = "1.6.4"
composeActivity = "1.7.0"
hiltNavigationCompose = "1.0.0"
accompanistSystemUiController = "0.29.1-alpha"
retrofit = "2.9.0"

turbineTest = "0.12.1"
mockitoTest = "4.1.0"
mockitoInlineTest = "4.11.0"
kotlinCoroutinesTest = "1.6.4"
junitTest = "4.13.2"
jsonTest = "20210307"

androidMockitoTest = "4.0.0"
androidJunitTest = "1.1.5"
androidTestEspressoCore = "3.5.1"
androidTestUiAutomator = "2.2.0"
androidTestBenchmark = "1.1.1"

leakCanary = "2.10"

androidxMetricsPerformance = "1.0.0-alpha04"
androidxProfileInstaller = "1.3.0"

androidGradlePlugin = "7.4.2"
androidJetBrainsKotlin = "1.7.20"
androidTest = "7.4.2"
androidJetBrainsKotlinJVM = "1.7.10"
androidKSPPlugin = "1.7.22-1.0.8"
kotilnCoroutinesCore = "1.6.4"
coilCompose = "2.2.2"
lottie = "5.2.0"
androidxConstraintLayout = "1.0.4"
androidxPalette = "1.0.0"
moshi = "1.14.0"
androidxAppCompat = "1.6.1"
androidxDataStore = "1.0.0"
testRunner = "1.5.2"

[libraries]
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidCore" }

compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-material = { group = "androidx.compose.material", name = "material", version.ref = "composeMaterial" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "composeActivity" }
compose-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "composeConstraintLayout" }
compose-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "composeLifecycle" }
compose-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "composeLifecycle" }
compose-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "composeLifecycle" }
#compose-material-window-size-class = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "composeMaterial3" }
#compose-material-3 = { group = "androidx.compose.material3", name = "material3", version.ref = "composeMaterial3" }

hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

navigation-destinations-core = { group = "io.github.raamcosta.compose-destinations", name = "core", version.ref = "composeDestinations" }
navigation-destinations-animations-core = { group = "io.github.raamcosta.compose-destinations", name = "animations-core", version.ref = "composeDestinations" }
navigation-destinations-compiler = { group = "io.github.raamcosta.compose-destinations", name = "ksp", version.ref = "composeDestinations" }

accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanistSystemUiController" }

test-turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbineTest" }
test-mockito = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockitoTest" }
test-mockito-inline = { group = "org.mockito", name = "mockito-inline", version.ref = "mockitoInlineTest" }
test-kotlin-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinCoroutinesTest" }
test-junit = { group = "junit", name = "junit", version.ref = "junitTest" }
test-json = { group = "org.json", name = "json", version.ref = "jsonTest" }

debug-leak-canary = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakCanary" }

androidx-metrics-performance = { group = "androidx.metrics", name = "metrics-performance", version.ref = "androidxMetricsPerformance" }
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "androidxProfileInstaller" }

test-android-hilt-kapt = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
test-android-hilt = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
test-android-mockito = { group = "org.mockito", name = "mockito-android", version.ref = "androidMockitoTest" }
test-android-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidJunitTest" }
test-android-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidTestEspressoCore" }
test-android-compose-ui = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose" }
test-android-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
test-android-compose-ui-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose" }
test-android-automator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "androidTestUiAutomator" }
test-android-benchmark = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "androidTestBenchmark" }
test-android-runner = { group = "androidx.test", name = "runner", version.ref = "testRunner" }

moshi = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }
moshi-adapters = { group = "com.squareup.moshi", name = "moshi-adapters", version.ref = "moshi" }
moshi-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }
kotlin-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotilnCoroutinesCore" }

retrofit = {group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit"}
retrofit-converter-moshi = {group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit"}

coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "coilCompose" }
lottie = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout-core", version.ref = "androidxConstraintLayout" }
androidx-palette = { group = "androidx.palette", name = "palette-ktx", version.ref = "androidxPalette" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidx-room = { group = "androidx.room", name = "room-rxjava3", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidxDataStore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-jetbrains-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "androidJetBrainsKotlin" }
android-test = { id = "com.android.test", version.ref = "androidTest" }
android-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "androidJetBrainsKotlinJVM" }
ksp = { id = "com.google.devtools.ksp", version.ref = "androidKSPPlugin" }
kotlin-kapt = { id = "kotlin-kapt" }
hilt = { id = "dagger.hilt.android.plugin", version.ref = "hilt" }
